// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OverwatchAPI.DATA;

#nullable disable

namespace OverwatchAPI.Migrations
{
    [DbContext(typeof(OverwatchDbContext))]
    partial class OverwatchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OverwatchAPI.MODELS.DetalleHabilidad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("HabilidadesID")
                        .HasColumnType("int");

                    b.Property<int>("HeroID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("DetalleHabilidades");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            HabilidadesID = 1,
                            HeroID = 1
                        },
                        new
                        {
                            ID = 2,
                            HabilidadesID = 2,
                            HeroID = 1
                        });
                });

            modelBuilder.Entity("OverwatchAPI.MODELS.Habilidad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descripción")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DetalleID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Habilidades");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Descripción = "Blink",
                            DetalleID = 1
                        },
                        new
                        {
                            ID = 2,
                            Descripción = "Recall",
                            DetalleID = 1
                        });
                });

            modelBuilder.Entity("OverwatchAPI.MODELS.Hero", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Heroes");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Tracer es un ágil y valiente piloto de pruebas que se convirtió en una heroína del tiempo. Su habilidad para manipular el tiempo la convierte en una fuerza formidable en el campo de batalla, permitiéndole teletransportarse rápidamente y deshacer los daños recibidos.",
                            Name = "Tracer"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Reaper es un misterioso mercenario que esconde su rostro bajo una máscara de calavera. Utiliza una combinación de habilidades oscuras y tácticas sigilosas para acechar a sus enemigos y eliminarlos con su par de escopetas infernales.",
                            Name = "Reaper"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
